default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: <%= Rails.application.secrets.db_host %>
  username: <%= Rails.application.secrets.db_username %>
  password: <%= Rails.application.secrets.db_password %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog
