defaults: &defaults
  workers:  4
  backlog:  1024
  listen:   'tmp/sockets/blog.sock'
  pid:      'tmp/pids/unicorn.pid'
  pid_lock: 'tmp/pids/unicorn.pid.lock'
  stdout:   'log/unicorn-stdout.log'
  stderr:   'log/unicorn-stderr.log'

development:
  <<: *defaults
  listen: '127.0.0.1:3001'

test:
  <<: *defaults

production:
  <<: *defaults
